POST {{base_url}}/v1/producers/picture
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{access_token}}

--WebAppBoundary
Content-Disposition: form-data; name="picture"; filename="producer_picture.jpg"
Content-Type: image/jpeg

< ../.images/producer_picture.jpg