global using Asp.Versioning;
global using ResultExtensions;
global using Eventify.Presentation.Common.Controllers;
global using Eventify.Presentation.Common.Requests;
global using Mapster;
global using MediatR;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using ResultExtensions.AspNetCore.Mvc;