POST {{base_url}}/v1/tickets/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "event_id": "{{event_id}}",
  "name": "Day 4",
  "description": "The first day of the event.",
  "price": 17.00,
  "quantity": 50,
  "quantity_per_sale": 2,
  "sale_start": null,
  "sale_end": null
}

> {%
if (response.status === 201) {
  client.global.set('ticket_id', response.body.id);
}
%}