global using ErrorOr;
global using Eventify.TestUtils.Assertions;
global using Eventify.TestUtils.Constants;
global using Eventify.TestUtils.Factories;
global using FluentAssertions;
global using JetBrains.Annotations;
global using FakeItEasy;
global using Mapster;
global using Xunit;